{application,griffin_ssg,
             [{modules,['Elixir.GriffinSSG','Elixir.GriffinSSG.Filesystem',
                        'Elixir.GriffinSSG.Filesystem.Watcher',
                        'Elixir.GriffinSSG.Layouts',
                        'Elixir.GriffinSSG.Web.Plug',
                        'Elixir.Mix.Tasks.Grf.Build',
                        'Elixir.Mix.Tasks.Grf.New.Page',
                        'Elixir.Mix.Tasks.Grf.Server']},
              {optional_applications,[]},
              {applications,[kernel,stdlib,elixir,logger,eex,earmark,
                             file_system,plug_cowboy,plug_live_reload,slugify,
                             yaml_elixir,assertions]},
              {description,"Griffin static site generator"},
              {registered,[]},
              {vsn,"0.3.0"}]}.
