{application,assertions,
             [{modules,['Elixir.Assertions','Elixir.Assertions.Absinthe',
                        'Elixir.Assertions.AbsintheCase',
                        'Elixir.Assertions.Case',
                        'Elixir.Assertions.Changeset',
                        'Elixir.Assertions.Comparisons']},
              {optional_applications,[]},
              {applications,[kernel,stdlib,elixir]},
              {description,"Helpful functions with great error messages to help you write better tests."},
              {registered,[]},
              {vsn,"0.20.1"}]}.
